"""empty message

Revision ID: a399787daa1e
Revises: f5a34835b271
Create Date: 2021-06-20 14:32:51.373498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a399787daa1e'
down_revision = 'f5a34835b271'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
    venue = sa.sql.table('Venue', sa.sql.column('seeking_talent'))
    op.execute(
        venue
        .update()
        .where(venue.columns.seeking_talent==sa.sql.null())
        .values(seeking_talent=False)
    )
    op.alter_column('Venue', 'seeking_talent', nullable=False)
    op.add_column('Venue', sa.Column('seeking_description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'seeking_description')
    op.drop_column('Venue', 'seeking_talent')
    # ### end Alembic commands ###
