"""empty message

Revision ID: b5658f866fa4
Revises: a5a5e318846c
Create Date: 2021-06-23 01:56:29.504114

"""
from alembic import op
import sqlalchemy as sa
from forms import genres


# revision identifiers, used by Alembic.
revision = 'b5658f866fa4'
down_revision = 'a5a5e318846c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('venues_genres')
    op.drop_table('artists_genres')
    op.add_column('artists', sa.Column('genres', sa.ARRAY(sa.String())))
    op.add_column('venues', sa.Column('genres', sa.ARRAY(sa.String())))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'genres')
    op.drop_column('artists', 'genres')
    op.create_table(
        'artists_genres',
        sa.Column(
            'artist_id', sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            'genre_id', sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ['artist_id'],
            ['artists.id'],
            name='artists_genres_artist_id_fkey'
        ),
        sa.ForeignKeyConstraint(
            ['genre_id'], ['genres.id'], name='artists_genres_genre_id_fkey'
        ),
        sa.PrimaryKeyConstraint(
            'artist_id', 'genre_id', name='Artist_Genres_pkey'
        )
    )
    op.create_table(
        'venues_genres',
        sa.Column(
            'venue_id', sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            'genre_id', sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ['genre_id'], ['genres.id'], name='venues_genres_genre_id_fkey'
        ),
        sa.ForeignKeyConstraint(
            ['venue_id'], ['venues.id'], name='venues_genres_venue_id_fkey'
        ),
        sa.PrimaryKeyConstraint(
            'venue_id', 'genre_id', name='Venue_Genres_pkey'
        )
    )
    # ### end Alembic commands ###
