"""empty message

Revision ID: f070dfa04cbf
Revises: a5c832609ff3
Create Date: 2021-06-21 23:15:22.325082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f070dfa04cbf'
down_revision = 'a5c832609ff3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('Venue', 'venues')
    op.rename_table('Artist', 'artists')
    op.rename_table('Show', 'shows')
    op.rename_table('Genre', 'genres')
    op.rename_table('Venue_Genres', 'venues_genres')
    op.rename_table('Artist_Genres', 'artists_genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('venues', 'Venue')
    op.rename_table('artists', 'Artist')
    op.rename_table('shows', 'Show')
    op.rename_table('genres', 'Genre')
    op.rename_table('venues_genres', 'Venue_Genres')
    op.rename_table('artists_genres', 'Artist_Genres')
    # ### end Alembic commands ###
