"""empty message

Revision ID: 3dea1998305e
Revises: 5b361d98a5e6
Create Date: 2021-06-20 17:16:14.005412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dea1998305e'
down_revision = '5b361d98a5e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'Artist',
        sa.Column('website_link', sa.String(), nullable=True),
    )
    op.add_column(
        'Artist',
        sa.Column('seeking_talent', sa.Boolean(), nullable=True),
    )
    artist = sa.sql.table('Artist', sa.sql.column('seeking_talent'))
    op.execute(
        artist
        .update()
        .where(artist.columns.seeking_talent == sa.sql.null())
        .values(seeking_talent=False)
    )
    op.alter_column('Artist', 'seeking_talent', nullable=False)
    op.add_column(
        'Artist',
        sa.Column('seeking_description', sa.String(), nullable=True)
    )
    op.drop_column('Artist', 'genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'Artist',
        sa.Column(
            'genres',
            sa.VARCHAR(length=120),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column('Artist', 'seeking_description')
    op.drop_column('Artist', 'seeking_talent')
    op.drop_column('Artist', 'website_link')
    # ### end Alembic commands ###
