"""empty message

Revision ID: 5fbc56e31072
Revises: 79219dea6124
Create Date: 2021-06-20 17:37:07.547858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fbc56e31072'
down_revision = '79219dea6124'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'Artist',
        'seeking_talent',
        new_column_name='seeking_venue',
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'Artist',
        'seeking_venue',
        new_column_name='seeking_talent'
    )
    # ### end Alembic commands ###
