"""empty message

Revision ID: 79219dea6124
Revises: 3dea1998305e
Create Date: 2021-06-20 17:18:50.263290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79219dea6124'
down_revision = '3dea1998305e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'Artist_Genres',
        sa.Column('artist_id', sa.Integer(), nullable=False),
        sa.Column('genre_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], ),
        sa.ForeignKeyConstraint(['genre_id'], ['Genre.id'], ),
        sa.PrimaryKeyConstraint('artist_id', 'genre_id'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Artist_Genres')
    # ### end Alembic commands ###
