"""empty message

Revision ID: a5c832609ff3
Revises: 5fbc56e31072
Create Date: 2021-06-20 19:31:32.909221

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a5c832609ff3'
down_revision = '5fbc56e31072'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Show', 'datetime', new_column_name='start_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Show', 'start_time', new_column_name='datetime')
    # ### end Alembic commands ###
